// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cookbook.Infrastructure.db;

#nullable disable

namespace cookbook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429092924_app_init")]
    partial class app_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("cookbook.Domain.Entities.File", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsTitle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_title");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<string>("PreviewFileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_file_id");

                    b.Property<string>("RecipeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recipe_id");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("PreviewFileId")
                        .HasDatabaseName("ix_files_preview_file_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_files_recipe_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("cookbook.Domain.Entities.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("Descriptions")
                        .HasColumnType("TEXT")
                        .HasColumnName("descriptions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_recipes_title");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("cookbook.Domain.Entities.RecipeTag", b =>
                {
                    b.Property<string>("RecipeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("recipe_id");

                    b.Property<string>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_id");

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_data");

                    b.HasKey("RecipeId", "TagId")
                        .HasName("pk_recipe_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_recipe_tag_tag_id");

                    b.ToTable("recipe_tag", (string)null);
                });

            modelBuilder.Entity("cookbook.Domain.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("cookbook.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("cookbook.Domain.Entities.File", b =>
                {
                    b.HasOne("cookbook.Domain.Entities.File", "PreviewFile")
                        .WithMany()
                        .HasForeignKey("PreviewFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_files_files_preview_file_id");

                    b.HasOne("cookbook.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Files")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("fk_files_recipes_recipe_id");

                    b.Navigation("PreviewFile");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("cookbook.Domain.Entities.RecipeTag", b =>
                {
                    b.HasOne("cookbook.Domain.Entities.Recipe", null)
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tag_recipes_recipe_id");

                    b.HasOne("cookbook.Domain.Entities.Tag", null)
                        .WithMany("RecipeTag")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_tag_tags_tag_id");
                });

            modelBuilder.Entity("cookbook.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("cookbook.Domain.Entities.Tag", b =>
                {
                    b.Navigation("RecipeTag");
                });
#pragma warning restore 612, 618
        }
    }
}
